# -*- coding: utf-8 -*-
"""도로당 평균속도 분석

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hmDXaqlJwY1B_HxFysQjiBAZiL7UktdZ
"""

#나눔폰트 다운로드
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.font_manager as fm
import seaborn as sns

#상습정체시간별 도로 속도 데이터
df_or=pd.read_excel("/content/drive/MyDrive/세종시 데이터 분석/data/상습정체시간(도로)_셀맵 (1).xls")

#데이터 전처리(출퇴근시간 평균속도)
df_V_k=df_or.replace('-',0)
df_V_k['New name']=df_V_k['도로명']+' '+'('+df_V_k['도로']+')'
df_V=df_V_k[['New name','07','08','09','17','18','19']]
df_V=df_V.replace(0,np.NaN)
df_V.isnull().sum()
df_V_means=df_V.mean(skipna=True,axis=1)
df_V_means=df_V_means.astype(int)
df_V['평균통행속도']=df_V_means
df=df_V.sort_values('평균통행속도',ascending=True)
df10=df.head(10)

#seaborn bar graph
plt.figure(figsize=(20,8))
plt.rc('font', family='NanumBarunGothic')
sns.barplot(data=df10,x='평균통행속도',y='New name')
plt.show()

